DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

DROP TABLE IF EXISTS Kakao;
CREATE TABLE Kakao (
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
nickName VARCHAR(30) NOT NULL
);

SELECT * FROM Kakao;